title: Diamond Dust Ice
email:  thaiiceproduction@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  © Copyright 2014, Diamond Dust. All Rights Reserved.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wwww.diamonddustice.com"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
